In [32]:
import torch

In [33]:
sentence = torch.Tensor(
    [
        0, #can
        7, #you
        1, #help
        2, #me 
        5, #to
        6, #translate
        4, #this
        3, #sentence
    ]
)

In [34]:
sentence.long()

tensor([0, 7, 1, 2, 5, 6, 4, 3])

In [35]:
#after the sentence being encoded in 
torch.manual_seed(123)
embed = torch.nn.Embedding(10, 16)
embedded_sentence = embed(sentence.long()).detach()
embedded_sentence.shape


torch.Size([8, 16])

In [36]:
omega  = torch.empty(8, 8)
for i, x_i in enumerate(embedded_sentence):
    for j, x_j in enumerate(embedded_sentence):
        omega[i,j] = torch.dot(x_i,x_j)

In [37]:

omega_mat = embedded_sentence.matmul(embedded_sentence.T)

In [38]:
#verify if the matrix multiplication produce the expected result btw omega_mat and omega.
#In a project no need to go for "for loop" due to it inefficient compare to matrix multiplication.
torch.allclose(omega_mat, omega)

True

In [39]:
#attention weight normalization using softmax function 
import torch.nn.functional as F
attention_weights  = F.softmax(omega_mat, dim = 1)
attention_weights.shape

torch.Size([8, 8])

In [40]:
attention_weights.sum(dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [41]:
context_vector = torch.matmul(attention_weights, embedded_sentence)
context_vector

tensor([[ 3.3420e-01, -1.8324e-01, -3.0218e-01, -5.7772e-01,  3.5662e-01,
          6.6452e-01, -2.0998e-01, -3.7798e-01,  7.6537e-01, -1.1946e+00,
          6.9960e-01, -1.4067e+00,  1.7021e-01,  1.8838e+00,  4.8729e-01,
          2.4730e-01],
        [-9.3975e-01, -4.6856e-01,  1.0311e+00, -2.8192e-01,  4.9373e-01,
         -1.2896e-02, -2.7327e-01, -7.6358e-01,  1.3958e+00, -9.9543e-01,
         -7.1287e-04,  1.2449e+00, -7.8077e-02,  1.2765e+00, -1.4589e+00,
         -2.1601e+00],
        [-7.7021e-02, -1.0205e+00, -1.6895e-01,  9.1776e-01,  1.5810e+00,
          1.3010e+00,  1.2753e+00, -2.0095e-01,  4.9647e-01, -1.5723e+00,
          9.6657e-01, -1.1481e+00, -1.1589e+00,  3.2547e-01, -6.3151e-01,
         -2.8400e+00],
        [-1.3679e+00,  1.0614e-01, -2.1317e+00,  1.0480e+00, -3.7127e-01,
         -9.1234e-01, -4.3802e-01, -1.0329e+00,  9.3425e-01,  1.5453e+00,
          5.7218e-01, -1.8049e-01, -6.0456e-03, -8.8691e-02,  2.0559e-01,
         -5.2292e-01],
        [ 2.5444e-01

In [42]:
context_vector.shape

torch.Size([8, 16])